### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by stevetoro** [ChristianTudor/prj-rev-bwfs-dasmoto#6]
https://github.com/ChristianTudor/prj-rev-bwfs-dasmoto/blob/master/Dasmoto%60s/rescources/style.css#L12-L31

You're repeating the majority of the styles in these CSS rules. Consolidate them into a more general selector to remove repetition.

```css
h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```
